// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationMVCBatch3.Models;

#nullable disable

namespace WebApplicationMVCBatch3.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20250625121716_P12")]
    partial class P12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.AccountName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccountName");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Books", b =>
                {
                    b.Property<int>("BID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BID"));

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentsSID")
                        .HasColumnType("int");

                    b.HasKey("BID");

                    b.HasIndex("StudentsSID");

                    b.ToTable("books");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.C1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("c1");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.C12", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("c12");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Country", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cid"));

                    b.Property<string>("Cname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cid");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Emp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("emps");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Husband", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("wifeRefID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("wifeRefID");

                    b.ToTable("husbands");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Location", b =>
                {
                    b.Property<int>("EmpID")
                        .HasColumnType("int");

                    b.Property<string>("LocAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpID");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.One", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("twoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("twoId");

                    b.ToTable("ones");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Orders", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("OrderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.ToTable("tbl_NewOrders");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.P1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("C1Id")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("C1Id");

                    b.ToTable("p1");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.P12", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("C12Id")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("C12Id");

                    b.ToTable("p12");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.PatientAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientID")
                        .IsUnique();

                    b.ToTable("patientAddress");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.States", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sid"));

                    b.Property<int>("CountryCid")
                        .HasColumnType("int");

                    b.Property<int>("refid")
                        .HasColumnType("int");

                    b.Property<string>("sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sid");

                    b.HasIndex("CountryCid");

                    b.ToTable("States");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Students", b =>
                {
                    b.Property<int>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SID"));

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SID");

                    b.ToTable("students");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Two", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OneEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("twos");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountNameId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNameId");

                    b.ToTable("UserAccount");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("userProfile");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Tbl_EmpData");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Wife", b =>
                {
                    b.Property<int>("RefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefID"));

                    b.Property<string>("WName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefID");

                    b.ToTable("wives");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Books", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.Students", "Students")
                        .WithMany("Books")
                        .HasForeignKey("StudentsSID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Husband", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.Wife", "wife")
                        .WithMany()
                        .HasForeignKey("wifeRefID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("wife");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Location", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.Emp", "Emp")
                        .WithOne("Location")
                        .HasForeignKey("WebApplicationMVCBatch3.Models.Location", "EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.One", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.Two", "two")
                        .WithMany()
                        .HasForeignKey("twoId");

                    b.Navigation("two");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.P1", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.AccountName", "C1")
                        .WithMany()
                        .HasForeignKey("C1Id");

                    b.Navigation("C1");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.P12", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.C12", "C12")
                        .WithMany()
                        .HasForeignKey("C12Id");

                    b.Navigation("C12");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.PatientAddress", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.Patient", "Patient")
                        .WithOne("PatientAddress")
                        .HasForeignKey("WebApplicationMVCBatch3.Models.PatientAddress", "PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.States", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryCid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.UserAccount", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.AccountName", "AccountName")
                        .WithMany()
                        .HasForeignKey("AccountNameId");

                    b.Navigation("AccountName");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.UserProfile", b =>
                {
                    b.HasOne("WebApplicationMVCBatch3.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("WebApplicationMVCBatch3.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Emp", b =>
                {
                    b.Navigation("Location");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Patient", b =>
                {
                    b.Navigation("PatientAddress");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.Students", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApplicationMVCBatch3.Models.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
